### ISSUE TITLE
[RIP-46] Observability improvement for RocketMQ

### ISSUE THREAD

**Issue by ShadowySpirits** [apache/rocketmq#5350]
This issue aims to trace the progress of RIP-46.

Brief introduce:
Redesign metrics: embrace OpenTelemetry specification and implement a native metrics architecture for RocketMQ.

Link: [[RIP-46] Observability Improvement for RocketMQ](https://github.com/apache/rocketmq/wiki/RIP-46-Observability-improvement-for-RocketMQ)

Task:
- [x] Task1: Define the specification of metric. #5366
- [x] Task2: Implement metrics collector and exporter framework in broker and proxy. #5354 
- [x] Task3: Develop metrics for broker and proxy. #5448
- [ ] Task4: Backport new metrics to rocketmq-exporter.
- [ ] Task5: Other ecosystem work, like document, Grafana dashboard template, etc.

**Comment by GenerousMan** [comment]
Hello, I have completed some broker metrics related to timing and transaction messages. I will initiate a PR and link to this issue's task 3. I hope you can help review it if you have free time.
